<?php


namespace app\models\repositories;


use app\engine\App;

use app\models\entities\CartEntity;
use app\models\Entity;
use app\models\Repository;

class CartRepository extends Repository
{
    public function getCart($session_id = false) {
        $sql = "SELECT  p.id,
                        b.count,
                        p.title,
                        p.description,
                        p.price
                FROM `carts` b,
                     `products` p
                WHERE b.product_id = p.id
                  AND session_id = :session_id";

        return App::call()->db->queryAll($sql, ['session_id' => ($session_id)? $session_id : App::call()->session->getSession_id()]);
    }

    public function update(Entity $entity)
    {
        parent::update($entity); // TODO: Change the autogenerated stub
    }

    public function getEntityClass()
    {
        return CartEntity::class;
    }

    public function getTableName()
    {
        return "carts";
    }
}